export type VariantsValues = (typeof Variants)[keyof typeof Variants];
export const Variants = {
	BITTERSWEET_RED: 'bittersweet-red',
	BITTERSWEET_RED_DARK: 'bittersweet-red-dark',
	BITTERSWEET_RED_DARKER: 'bittersweet-red-darker',
	BITTERSWEET_RED_CONTENT: 'bittersweet-red-content',
	TEXAS_YELLOW: 'texas-yellow',
	TEXAS_YELLOW_DARK: 'texas-yellow-dark',
	TEXAS_YELLOW_DARKER: 'texas-yellow-darker',
	TEXAS_YELLOW_CONTENT: 'texas-yellow-content',
	FERN_GREEN: 'fern-green',
	FERN_GREEN_DARK: 'fern-green-dark',
	FERN_GREEN_DARKER: 'fern-green-darker',
	FERN_GREEN_CONTENT: 'fern-green-content',
	PICTON_BLUE: 'picton-blue',
	PICTON_BLUE_DARK: 'picton-blue-dark',
	PICTON_BLUE_DARKER: 'picton-blue-darker',
	PICTON_BLUE_CONTENT: 'picton-blue-content',
	AMETHYST_PURPLE: 'amethyst-purple',
	AMETHYST_PURPLE_DARK: 'amethyst-purple-dark',
	AMETHYST_PURPLE_DARKER: 'amethyst-purple-darker',
	AMETHYST_PURPLE_CONTENT: 'amethyst-purple-content',
	NEUTRAL_LIGHTER: 'gray-300',
	NEUTRAL_LIGHT: 'gray-400',
	NEUTRAL: 'gray-500',
	NEUTRAL_DARK: 'gray-600',
	NEUTRAL_DARKER: 'gray-700',
	NEUTRAL_CONTENT: 'gray-800'
} as const;

export type BgColorsValues = (typeof BgColors)[keyof typeof BgColors];
export const BgColors = {
	BITTERSWEET_RED: 'bg-bittersweet-red',
	BITTERSWEET_RED_DARK: 'bg-bittersweet-red-dark',
	BITTERSWEET_RED_DARKER: 'bg-bittersweet-red-darker',
	BITTERSWEET_RED_CONTENT: 'bg-bittersweet-red-content',
	TEXAS_YELLOW: 'bg-texas-yellow',
	TEXAS_YELLOW_DARK: 'bg-texas-yellow-dark',
	TEXAS_YELLOW_DARKER: 'bg-texas-yellow-darker',
	TEXAS_YELLOW_CONTENT: 'bg-texas-yellow-content',
	FERN_GREEN: 'bg-fern-green',
	FERN_GREEN_DARK: 'bg-fern-green-dark',
	FERN_GREEN_DARKER: 'bg-fern-green-darker',
	FERN_GREEN_CONTENT: 'bg-fern-green-content',
	PICTON_BLUE: 'bg-picton-blue',
	PICTON_BLUE_DARK: 'bg-picton-blue-dark',
	PICTON_BLUE_DARKER: 'bg-picton-blue-darker',
	PICTON_BLUE_CONTENT: 'bg-picton-blue-content',
	AMETHYST_PURPLE: 'bg-amethyst-purple',
	AMETHYST_PURPLE_DARK: 'bg-amethyst-purple-dark',
	AMETHYST_PURPLE_DARKER: 'bg-amethyst-purple-darker',
	AMETHYST_PURPLE_CONTENT: 'bg-amethyst-purple-content',
	NEUTRAL_LIGHTER: 'bg-gray-300',
	NEUTRAL_LIGHT: 'bg-gray-400',
	NEUTRAL: 'bg-gray-500',
	NEUTRAL_DARK: 'bg-gray-600',
	NEUTRAL_DARKER: 'bg-gray-700',
	NEUTRAL_CONTENT: 'bg-gray-800'
} as const;

export type TextColorsValues = (typeof TextColors)[keyof typeof TextColors];
export const TextColors = {
	BITTERSWEET_RED: 'text-bittersweet-red',
	BITTERSWEET_RED_DARK: 'text-bittersweet-red-dark',
	BITTERSWEET_RED_DARKER: 'text-bittersweet-red-darker',
	BITTERSWEET_RED_CONTENT: 'text-bittersweet-red-content',
	TEXAS_YELLOW: 'text-texas-yellow',
	TEXAS_YELLOW_DARK: 'text-texas-yellow-dark',
	TEXAS_YELLOW_DARKER: 'text-texas-yellow-darker',
	TEXAS_YELLOW_CONTENT: 'text-texas-yellow-content',
	FERN_GREEN: 'text-fern-green',
	FERN_GREEN_DARK: 'text-fern-green-dark',
	FERN_GREEN_DARKER: 'text-fern-green-darker',
	FERN_GREEN_CONTENT: 'text-fern-green-content',
	PICTON_BLUE: 'text-picton-blue',
	PICTON_BLUE_DARK: 'text-picton-blue-dark',
	PICTON_BLUE_DARKER: 'text-picton-blue-darker',
	PICTON_BLUE_CONTENT: 'text-picton-blue-content',
	AMETHYST_PURPLE: 'text-amethyst-purple',
	AMETHYST_PURPLE_DARK: 'text-amethyst-purple-dark',
	AMETHYST_PURPLE_DARKER: 'text-amethyst-purple-darker',
	AMETHYST_PURPLE_CONTENT: 'text-amethyst-purple-content',
	NEUTRAL_LIGHTER: 'text-gray-300',
	NEUTRAL_LIGHT: 'text-gray-400',
	NEUTRAL: 'text-gray-500',
	NEUTRAL_DARK: 'text-gray-600',
	NEUTRAL_DARKER: 'text-gray-700',
	NEUTRAL_CONTENT: 'text-gray-800'
} as const;

export type BorderColorsValues =
	(typeof BorderColors)[keyof typeof BorderColors];
export const BorderColors = {
	BITTERSWEET_RED: 'border-bittersweet-red',
	BITTERSWEET_RED_DARK: 'border-bittersweet-red-dark',
	BITTERSWEET_RED_DARKER: 'border-bittersweet-red-darker',
	BITTERSWEET_RED_CONTENT: 'border-bittersweet-red-content',
	TEXAS_YELLOW: 'border-texas-yellow',
	TEXAS_YELLOW_DARK: 'border-texas-yellow-dark',
	TEXAS_YELLOW_DARKER: 'border-texas-yellow-darker',
	TEXAS_YELLOW_CONTENT: 'border-texas-yellow-content',
	FERN_GREEN: 'border-fern-green',
	FERN_GREEN_DARK: 'border-fern-green-dark',
	FERN_GREEN_DARKER: 'border-fern-green-darker',
	FERN_GREEN_CONTENT: 'border-fern-green-content',
	PICTON_BLUE: 'border-picton-blue',
	PICTON_BLUE_DARK: 'border-picton-blue-dark',
	PICTON_BLUE_DARKER: 'border-picton-blue-darker',
	PICTON_BLUE_CONTENT: 'border-picton-blue-content',
	AMETHYST_PURPLE: 'border-amethyst-purple',
	AMETHYST_PURPLE_DARK: 'border-amethyst-purple-dark',
	AMETHYST_PURPLE_DARKER: 'border-amethyst-purple-darker',
	AMETHYST_PURPLE_CONTENT: 'border-amethyst-purple-content',
	NEUTRAL_LIGHTER: 'border-gray-300',
	NEUTRAL_LIGHT: 'border-gray-400',
	NEUTRAL: 'border-gray-500',
	NEUTRAL_DARK: 'border-gray-600',
	NEUTRAL_DARKER: 'border-gray-700',
	NEUTRAL_CONTENT: 'border-gray-800'
} as const;

export type BoxShadowsValues =
	(typeof BoxShadowsValues)[keyof typeof BoxShadowsValues];
export const BoxShadowsValues = {
	BITTERSWEET_RED: 'shadow-bittersweet-red',
	BITTERSWEET_RED_DARK: 'shadow-bittersweet-red-dark',
	BITTERSWEET_RED_DARKER: 'shadow-bittersweet-red-darker',
	BITTERSWEET_RED_CONTENT: 'shadow-bittersweet-red-content',
	TEXAS_YELLOW: 'shadow-texas-yellow',
	TEXAS_YELLOW_DARK: 'shadow-texas-yellow-dark',
	TEXAS_YELLOW_DARKER: 'shadow-texas-yellow-darker',
	TEXAS_YELLOW_CONTENT: 'shadow-texas-yellow-content',
	FERN_GREEN: 'shadow-fern-green',
	FERN_GREEN_DARK: 'shadow-fern-green-dark',
	FERN_GREEN_DARKER: 'shadow-fern-green-darker',
	FERN_GREEN_CONTENT: 'shadow-fern-green-content',
	PICTON_BLUE: 'shadow-picton-blue',
	PICTON_BLUE_DARK: 'shadow-picton-blue-dark',
	PICTON_BLUE_DARKER: 'shadow-picton-blue-darker',
	PICTON_BLUE_CONTENT: 'shadow-picton-blue-content',
	AMETHYST_PURPLE: 'shadow-amethyst-purple',
	AMETHYST_PURPLE_DARK: 'shadow-amethyst-purple-dark',
	AMETHYST_PURPLE_DARKER: 'shadow-amethyst-purple-darker',
	AMETHYST_PURPLE_CONTENT: 'shadow-amethyst-purple-content',
	NEUTRAL_LIGHTER: 'shadow-gray-300',
	NEUTRAL_LIGHT: 'shadow-gray-400',
	NEUTRAL: 'shadow-gray-500',
	NEUTRAL_DARK: 'shadow-gray-600',
	NEUTRAL_DARKER: 'shadow-gray-700',
	NEUTRAL_CONTENT: 'shadow-gray-800'
} as const;
